import { Fragment } from "react";
import ImageSpriteComponent, { AtlasType } from "react-sprite-image-atlas";
import atlas from "./configFiles/robot_sprites_atlas.json";
import "./App.css";

const marioAtlas: AtlasType = {
  frames: [
    {
      filename: "tile001",
      frame: {
        w: 16,
        h: 32,
        x: 0,
        y: 0,
      },
    },
    {
      filename: "tile003",
      frame: {
        w: 16,
        h: 32,
        x: 16,
        y: 0,
      },
    },
    {
      filename: "tile002",
      frame: {
        w: 16,
        h: 32,
        x: 32,
        y: 0,
      },
    },
    {
      filename: "tile004",
      frame: {
        w: 16,
        h: 32,
        x: 48,
        y: 0,
      },
    },
  ],
};
const frames = ["damage_sprite_1", "damage_sprite_2", "damage_sprite_3"];
function App() {
  return (
    <div className="App">
      <h1>react-sprite-image-atlas</h1>
      <article>
        <h2>Example with File configuration</h2>
        <p>
          In this example Sprite Image and Atlas file is generated by{" "}
          <a href="https://gammafp.com/tool/atlas-packer/" target="_blank">
            https://gammafp.com/tool/atlas-packer/
          </a>
        </p>
        <div className="robot-sprites-container">
          {frames.map((frame) => (
            <Fragment key={frame}>
              <ImageSpriteComponent
                imageSrc="sprites/robot_sprites.png"
                atlasConfig={atlas}
                frameName={frame}
                center
                responsive={true}
                blockAtMaxSize={false}
              />
            </Fragment>
          ))}
        </div>
      </article>
      <article>
        <h2>Example with constants</h2>
        <div className="mario-sprites-container">
          <ImageSpriteComponent
            imageSrc="sprites/mario_sprites.png"
            atlasConfig={marioAtlas}
            frameName="tile001"
          />
          <ImageSpriteComponent
            imageSrc="sprites/mario_sprites.png"
            atlasConfig={marioAtlas}
            frameName="tile002"
          />
          <ImageSpriteComponent
            imageSrc="sprites/mario_sprites.png"
            atlasConfig={marioAtlas}
            frameName="tile003"
          />
          <ImageSpriteComponent
            imageSrc="sprites/mario_sprites.png"
            atlasConfig={marioAtlas}
            frameName="tile004"
          />
        </div>
      </article>
    </div>
  );
}

export default App;
